### ISSUE TITLE
meta节点的插入有没有修复呀。

### ISSUE THREAD

**Issue by lozn00** [duangsuse/AXMLEdit#2]
4哥的会导致无法安装。

**Comment by duangsuse** [comment]
这个文件格式... 据说和 ARSC 有点类似，但我找不到真正能用的定义... 目前我准备写一个 BinaryStreamIO 框架然后重写这个工具，我觉得可以先用 ，记得我当时要重构这玩意的原因就是 ApkTool 无法回编，只能手改 AXML...

学生党时间比较少做事慢请谅解

**Comment by duangsuse** [comment]
还有：我不清楚啥是 meta 节点，[这个]？不过应该是没有修复的... （我没改太多，因为我写这个的时候没啥技术）

[这个]: https://github.com/duangsuse/AXMLEdit/blob/master/src/main/java/cn/wjdiankong/axmledit/helper/AXmlEditor.java#L101

找这么看你说的 meta 节点应该是一个 XML tag, 并且应该不是 app tag 是么，那

```java
    private static String[] isNotAppTag = new String[] {
            "uses-permission", "uses-sdk", "compatible-screens", "instrumentation", "library",
            "original-package", "package-verifier", "permission", "permission-group", "permission-tree",
            "protected-broadcast", "resource-overlay", "supports-input", "supports-screens", "upgrade-key-set",
"uses-configuration", "uses-feature" };
```

加一个 `"meta"` 或许就可以了？

**Comment by duangsuse** [comment]
而且这个工具写的有点不够好看... 用 byte 数组加上一大堆工具，还把用副作用的辅助函数全加上一个无用的返回值，有些改变长度的函数又需要复制弄出新的数组来，手算各种偏移量选区，内存开销非常混乱，XmlPull 的流模式也不至于特别辣鸡，但是这个『接口』上没有流模式内部使用的解析方式也比较... 符合直觉... 其实不要用那么多，二进制流反而更好看
